version: 2

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp/workspace

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go test -v ./... -mod vendor

  release-controller:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: curl -fsSL https://get.docker.com/ -o docker-install.sh
      - run: sh docker-install.sh
      - run: |-
          mkdir -p ~/.docker && echo '{"experimental":"enabled"}' > ~/.docker/config.json
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: CONTROLLER_VERSION=${CIRCLE_TAG#"controller-"} make push-controller

  release-controller-with-db:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: curl -fsSL https://get.docker.com/ -o docker-install.sh
      - run: sh docker-install.sh
      - run: |-
          mkdir -p ~/.docker && echo '{"experimental":"enabled"}' > ~/.docker/config.json
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: CONTROLLER_WITH_DB_VERSION=${CIRCLE_TAG#"controller-"} make push-controller-with-db

  release-controller-with-db:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: CONTROLLER_WITH_DB_VERSION=${CIRCLE_TAG#"controller-"} make push-controller-with-db

  build-agent-binaries:
    docker:
      - image: circleci/golang:1.13
    steps:
      - *attach_workspace
      - checkout
      - run: mkdir -p ./dist/agent
      - run: AGENT_VERSION=${CIRCLE_TAG#"agent-"} make agent-binaries
      - run: mv dist /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist

  upload-agent-binaries:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - *attach_workspace
      - checkout
      - run: sudo pip install awscli
      - run: aws s3 sync /tmp/workspace/dist/agent s3://agent.deviceplane.com/

  release-cli:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: CLI_VERSION=${CIRCLE_TAG#"cli-"} make push-cli

  build-cli-binaries:
    docker:
      - image: circleci/golang:1.13
    steps:
      - *attach_workspace
      - checkout
      - run: mkdir -p ./dist/cli
      - run: CLI_VERSION=${CIRCLE_TAG#"cli-"} make cli-binaries
      - run: mv dist /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist

  upload-cli-binaries:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - *attach_workspace
      - checkout
      - run: sudo pip install awscli
      - run: aws s3 sync /tmp/workspace/dist/cli s3://cli.deviceplane.com/

  upload-cli-binary-redirects:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: sudo pip install awscli
      - run: CLI_VERSION=${CIRCLE_TAG#"cli-"} ./scripts/ci/upload-cli-binary-redirects

workflows:
  version: 2
  test_release:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release-controller:
          requires:
            - test
          filters:
            tags:
              only: /^controller.*/
            branches:
              ignore: /.*/
      - release-controller-with-db:
          requires:
            - test
          filters:
            tags:
              only: /^controller.*/
            branches:
              ignore: /.*/
      - build-agent-binaries:
          requires:
            - test
          filters:
            tags:
              only: /^agent.*/
            branches:
              ignore: /.*/
      - upload-agent-binaries:
          requires:
            - build-agent-binaries
          filters:
            tags:
              only: /^agent.*/
            branches:
              ignore: /.*/
      - release-cli:
          requires:
            - test
          filters:
            tags:
              only: /^cli.*/
            branches:
              ignore: /.*/
      - build-cli-binaries:
          requires:
            - test
          filters:
            tags:
              only: /^cli.*/
            branches:
              ignore: /.*/
      - upload-cli-binaries:
          requires:
            - build-cli-binaries
          filters:
            tags:
              only: /^cli.*/
            branches:
              ignore: /.*/
      - upload-cli-binary-redirects:
          requires:
            - upload-cli-binaries
          filters:
            tags:
              only: /^cli.*/
            branches:
              ignore: /.*/
